---

language: python
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - software-properties-common
    - python-pip
    - puppet

before_install:
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update

install:
  - sudo apt-get install -y ansible
  - pip install ansible-review

before_script:
  - ansible --version
  - ansible-playbook --version
  - ansible-review --version
  - git --version
  - puppet --version
  - python --version
  - whereis puppet

script:
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  - git ls-files | grep -Ei '^[^[:punct:]].+.(yaml|yml)$' | xargs ansible-review -q
  - ansible-playbook --check --diff -i localhost, -c local tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
