---

language: python

addons:
  apt:
    packages:
    - software-properties-common
    - python-pip
    - puppet

before_install:
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update

install:
  - sudo apt-get install -y ansible
  - pip install ansible-lint

before_script:
  - ansible --version
  - ansible-playbook --version
  - ansible-lint --version
  - git --version
  - puppet --version
  - python --version
  - whereis puppet

script:
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  - git ls-files | grep yml | grep -v travis | xargs ansible-lint
  - ansible-playbook --check --diff -i localhost, -c local tests/test.yml -e 'ansible_python_interpreter=/usr/bin/python3'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
