---

language: python
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - software-properties-common
    - python-pip
    - puppet

before_install:
  - sudo apt-add-repository -y ppa:ansible/ansible

install:
  - sudo apt-get install -y ansible
  - ansible-galaxy install deekayen.sadpuppet
  - pip install ansible-review

before_script:
  - ansible --version
  - ansible-review --version

script:
  - git ls-files | grep -Ei '^[^[:punct:]].+.(yaml|yml)$' | xargs ansible-review -q
  - ansible-playbook --check --diff -i localhost, -c local tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
