---
- name: Validate role variables.
  ansible.builtin.import_tasks: assert.yml
  tags:
    - always

- name: Use package manager to remove Puppet.
  ansible.builtin.package:
    name: "{{ puppet_packages }}"
    state: absent

- name: Ensure specific paths are absent.
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ puppet_paths }}"

- name: Print the operating system family.
  ansible.builtin.debug:
    var: ansible_os_family
    verbosity: 2

- name: Include Debian-family key removal.
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Include RedHat-family key removal.
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
