---

- hosts: all
  become: true

  tasks:
    - name: Install puppet.
      apt:
        name: puppet
      when: ansible_os_family == 'Debian'

    - name: Install puppet.
      yum:
        name: puppet
      when:
        - ansible_os_family is defined
        - ansible_os_family == "RedHat"
