---

- hosts: all
  become: true

  tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Install prereqs.
      apt:
        name:
          - gnupg
          - puppet
      when: ansible_os_family == 'Debian'

    - name: Install puppet.
      yum:
        name: puppet
      when:
        - ansible_os_family is defined
        - ansible_os_family == "RedHat"
